### ISSUE TITLE
Sharing iP code quality feedback [for @deeyonn]

### ISSUE THREAD

**Issue by soc-se-bot-red** [deeyonn/ip#4]
@deeyonn We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/jenny/util/Printer.java` lines `40-40`](https://github.com/deeyonn/ip/blob/f20b11ff3daf3f97d47d62f3eed548dd52f0bf0d/src/main/java/jenny/util/Printer.java#L40..L40):

```java

//        printLine();

```

Example from [`src/main/java/jenny/util/Printer.java` lines `44-44`](https://github.com/deeyonn/ip/blob/f20b11ff3daf3f97d47d62f3eed548dd52f0bf0d/src/main/java/jenny/util/Printer.java#L44..L44):

```java

//        printLine();

```

Example from [`src/main/java/jenny/util/Printer.java` lines `53-53`](https://github.com/deeyonn/ip/blob/f20b11ff3daf3f97d47d62f3eed548dd52f0bf0d/src/main/java/jenny/util/Printer.java#L53..L53):

```java

//        printLine();

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/jenny/JennyBot.java` lines `46-48`](https://github.com/deeyonn/ip/blob/f20b11ff3daf3f97d47d62f3eed548dd52f0bf0d/src/main/java/jenny/JennyBot.java#L46..L48):

```java

    /**
     * Run the JennyBot Application
     */

```

Example from [`src/main/java/jenny/JennyBot.java` lines `65-70`](https://github.com/deeyonn/ip/blob/f20b11ff3daf3f97d47d62f3eed548dd52f0bf0d/src/main/java/jenny/JennyBot.java#L65..L70):

```java

    /**
     * Run the user input as a command and returns the response from the application.
     *
     * @param input the command to be run.
     * @return the response from the application after running the command.
     */

```

Example from [`src/main/java/jenny/storage/Storage.java` lines `42-47`](https://github.com/deeyonn/ip/blob/f20b11ff3daf3f97d47d62f3eed548dd52f0bf0d/src/main/java/jenny/storage/Storage.java#L42..L47):

```java

    /**
     * Save the item to storage.
     *
     * @param t the item to store
     * @throws JennyException when runtime exceptions are thrown in the JennyBot application.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by deeyonn** [comment]
Resolved all mentioned issues. Thank you.
